# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161129_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desription',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
