# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161129_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desription',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
